version: '3.3'
services: 
  weewx:
   image: "martinwiest/weewx"
   container_name: weewx
   restart: always
   ports:
    - "80:80"
   volumes:
    - "./config:/home/weewx/config:rw"
   devices: 
    - "/dev/bus/usb:/dev/bus/usb"
    - "/dev/i2c-1:/dev/i2c-1"  
   environment:
    - TZ=Europe/Berlin       
