version: '3.3'
services: 
  weewx:
   build: .
   container_name: weewx2
   ports:
    - "80:80"
   volumes:
    - "./config:/home/weewx/config:rw"
   devices: 
    - "/dev/bus/usb:/dev/bus/usb"
   environment:
    - TZ=Europe/Berlin       
